services:
  server:
    build: .
    user: "${UID}:${GID}"
    ports:
      - "25565:25565/tcp"
      - "25575:25575/tcp"
    volumes:
      - ./data:/data
    env_file:
      - path: .env
        required: true
    restart: unless-stopped